route: fix check for NULL in nh_encap_dump()
  Error: REVERSE_INULL (CWE-476):
  libnl-3.6.0/lib/route/nexthop_encap.c:35: deref_ptr: Directly dereferencing pointer "rtnh_encap->ops".
  libnl-3.6.0/lib/route/nexthop_encap.c:37: check_after_deref: Null-checking "rtnh_encap->ops" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
  #   35|   		nh_encap_type2str(rtnh_encap->ops->encap_type));
  #   36|···
  #   37|-> 	if (rtnh_encap->ops && rtnh_encap->ops->dump)
  #   38|   		rtnh_encap->ops->dump(rtnh_encap->priv, dp);
  #   39|   }